### ISSUE TITLE
SEMQA Evaluation Metrics

### ISSUE THREAD

**Issue by arnavsinghvi11** [google-research-datasets/QuoteSum#1]
Hi there!

I was very interested in exploring the SEMQA task with the QuoteSum dataset and was wondering if there would be a release of the metrics implementations for fluency, preciseness and comprehensiveness. 

Thanks!

**Comment by TalSchuster** [comment]
Thanks! Yes we are planning to share code for computing the metrics. Meanwhile feel free to reach out if you have any questions.

**Comment by TalSchuster** [comment]
We've added the evaluation metrics to the repo.
