### ISSUE TITLE
Title Source Mixup

### ISSUE THREAD

**Issue by mosheber** [google-research-datasets/QuoteSum#2]
Hi @TalSchuster! 
The dataset is really good, I just noticed that in some examples, the titles contain the content of the passage, instead of the title, with the source being empty.

Is it possible to address that in the next version of the data?
<img width="1257" alt="Screenshot 2024-01-02 at 9 34 00" src="https://github.com/google-research-datasets/QuoteSum/assets/22236370/d9c4a716-9a0b-4927-af7d-7125b4cb6385">

**Comment by TalSchuster** [comment]
Hi @mosheber,

Thanks for bringing this to our attention! From a quick search for such instances I only see a single example (the one you attach above) with this parsing issue. Please let us know if you find any other issues.
In this example, the title should be "I Love the '80s 3-D" and the rest should appear in the source. We'll make sure to fix it in the next version.

**Comment by mosheber** [comment]
Thanks! I will apply the changes
